name = "Cornell Box"

[camera]
position = [0.278, 0.273, -0.800]
angle = [1.5707963267948966, -1.5707963267948966, 0.0]
fov = 39.3077
near = 0.500
far = 2.000

[[models]]
type = "WavefrontObj"
file = "cornell_box.obj"
scale = 0.001            # mm to m
